SYMMETRY - Tâche 6
==========
Étude de l'effet de 3 éléments de symétrie différents

In [34]:
from pymatgen.ext.matproj import MPRester
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer
from pprint import pprint
from pymatgen.io.cif import CifWriter
from pymatgen import Structure
from pymatgen import symmetry
from pymatgen.core.operations import SymmOp
from IPython.display import Image
from jupyter_jsmol.pymatgen import quick_view

In [57]:
#Obtenir informations sur le matériau (structure) et materials project id
with MPRester("k7Oj07sVAFLX1l2ahe") as m:
    structure = m.get_structure_by_material_id("mp-15790")
    analyzer = SpacegroupAnalyzer(structure)
    
#Maille conventionnelle
conven = analyzer.get_conventional_standard_structure()

#On génère la liste des symétries (au nombre de 12)
symetries_list = analyzer.get_symmetry_operations()

#On génère aussi les positions de tous les atomes de la maille conventionnelle
sites = conven.sites

print(sites)
print(symetries_list)

[PeriodicSite: Li (1.9455, 1.1232, 3.0894) [0.3333, 0.6667, 0.1667], PeriodicSite: Li (3.8910, -0.0000, 9.2683) [1.0000, 1.0000, 0.5000], PeriodicSite: Li (1.9455, -1.1232, 15.4472) [0.6667, 0.3333, 0.8333], PeriodicSite: Ho (0.0000, 0.0000, 0.0000) [0.0000, 0.0000, 0.0000], PeriodicSite: Ho (1.9455, -1.1232, 6.1789) [0.6667, 0.3333, 0.3333], PeriodicSite: Ho (1.9455, 1.1232, 12.3577) [0.3333, 0.6667, 0.6667], PeriodicSite: S (0.0000, 0.0000, 4.6386) [0.0000, 0.0000, 0.2502], PeriodicSite: S (1.9455, -1.1232, 1.5402) [0.6667, 0.3333, 0.0831], PeriodicSite: S (1.9455, -1.1232, 10.8175) [0.6667, 0.3333, 0.5836], PeriodicSite: S (1.9455, 1.1232, 7.7191) [0.3333, 0.6667, 0.4164], PeriodicSite: S (1.9455, 1.1232, 16.9964) [0.3333, 0.6667, 0.9169], PeriodicSite: S (0.0000, 0.0000, 13.8980) [0.0000, 0.0000, 0.7498]]
[Rot:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
tau
[0. 0. 0.], Rot:
[[-1.  0.  0.]
 [ 0. -1.  0.]
 [ 0.  0. -1.]]
tau
[0. 0. 0.], Rot:
[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
tau
[0. 0. 

Symétrie 1
---------------------------------



In [71]:
premiere_symetrie = symetries_list[1]

print ("Symétrie de ", premiere_symetrie.as_xyz_string())
print ("La matrice de rotation est \n", premiere_symetrie.rotation_matrix )
print ("Le vecteur de translation est \n", premiere_symetrie.translation_vector)

Symétrie de  -x, -y, -z
La matrice de rotation est 
 [[-1.  0.  0.]
 [ 0. -1.  0.]
 [ 0.  0. -1.]]
Le vecteur de translation est 
 [0. 0. 0.]


On va appliquer cette première symétrie à l'atome Ho situé aux coordonnées (0.6667, 0.3333, 0.3333). 

In [43]:
atome_first = [0.6667, 0.3333, 0.3333]
atomeaftersym1 = premiere_symetrie.operate(atome_first)

print ("Coordonnées avant opération :", atome_first)
print ("Coordonnées après opération :", atomeaftersym1)

Coordonnées avant opération : [0.6667, 0.3333, 0.3333]
Coordonnées après opération : [-0.6667 -0.3333 -0.3333]


On est donc bien dans un symétrie d'inversion par rapport à l'origine. On a pu vérifier cette symétrie et trouver ses coordonnées images à partir de l'atome Ho. On va maintenant représenter cela avec jsmol.

In [48]:
view = quick_view(conven)
display(view) 
view.script('draw SYMOP 2 {atomno=5}')

JsmolView(layout=Layout(align_self='stretch', height='400px'))

Symétrie 2
-------------

In [70]:
sec_sym = symetries_list[10]

print ("Symétrie de ", sec_sym.as_xyz_string())
print ("La matrice de rotation est \n", sec_sym.rotation_matrix )
print ("Le vecteur de translation est \n", sec_sym.translation_vector)

Symétrie de  -y, -x, -z
La matrice de rotation est 
 [[ 0. -1.  0.]
 [-1.  0.  0.]
 [ 0.  0. -1.]]
Le vecteur de translation est 
 [0. 0. 0.]


Au vu des informations, on remarque qu'on est dans une symétrie de plan miroir par rapport à x et y.
On applique la symétrie à l'atome numéro 9, S, situé aux coordonnées (0.6667, 0.3333, 0.5836).


In [66]:
atome_secon = [0.6667, 0.3333, 0.5836]
atomeaftersym2 = sec_sym.operate(atome_secon)

print ("Coordonnées avant opération :", atome_secon)
print ("Coordonnées après opération :", atomeaftersym2)

Coordonnées avant opération : [0.6667, 0.3333, 0.5836]
Coordonnées après opération : [-0.3333 -0.6667 -0.5836]


In [67]:
view = quick_view(conven)
display(view) 
view.script('draw SYMOP 11  {atomno=9}')

JsmolView(layout=Layout(align_self='stretch', height='400px'))

Symétrie 3
---------------




In [69]:
third_sym = symetries_list[7]

print ("Symétrie de ", third_sym.as_xyz_string())
print ("La matrice de rotation est \n", third_sym.rotation_matrix)
print ("Le vecteur de translation est \n", third_sym.translation_vector)

Symétrie de  z, y, x
La matrice de rotation est 
 [[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]
Le vecteur de translation est 
 [0. 0. 0.]


On applique la symétrie à l'atome numéro 1, Li, situé aux coordonnées (0.3333, 0.6667, 0.1667)

In [72]:
atome_third = [0.3333, 0.6667, 0.1667]
atomeaftersym3 = sec_sym.operate(atome_third)

print ("Coordonnées avant opération :", atome_third)
print ("Coordonnées après opération :", atomeaftersym3)

Coordonnées avant opération : [0.3333, 0.6667, 0.1667]
Coordonnées après opération : [-0.6667 -0.3333 -0.1667]


In [73]:
view = quick_view(conven)
display(view) 
view.script('draw SYMOP 8  {atomno=1}')

JsmolView(layout=Layout(align_self='stretch', height='400px'))